drenv: Disable minikube logging to stderr
This creates huge amount of unreadable output when minikube fails,
hiding actual error.

With this change we get useful error when minikube fail to start:

    drenv.commands.Error: command failed:
      command:
      - minikube
      - start
      - --profile
      - c1
      - --driver
      - kvm2
      - --container-runtime
      - containerd
      - --disk-size
      - 20g
      - --network
      - default
      - --nodes
      - '1'
      - --cni
      - auto
      - --cpus
      - '2'
      - --memory
      - 3g
      - --extra-config
      - kubelet.serialize-image-pulls=false
      exitcode: 80
      error: "! StartHost failed, but will try again: creating host: create: creating:\
        \ starting domain: waiting for IP: domain c1 didn't return IP after 1m30s\n* Failed\
        \ to start kvm2 VM. Running \"minikube delete -p c1\" may fix it: creating host:\
        \ create: creating: starting domain: waiting for IP: domain c1 didn't return IP\
        \ after 1m30s\nX Exiting due to GUEST_PROVISION: error provisioning guest: Failed\
        \ to start host: creating host: create: creating: starting domain: waiting for\
        \ IP: domain c1 didn't return IP after 1m30s\n*\n\u256D\u2500\u2500\u2500\u2500\
        \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\
        \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\
        \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\
        \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\
        \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\
        \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\
        \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u256E\n\u2502\
        \                                                                            \
        \                 \u2502\n\u2502    * If the above advice does not help, please\
        \ let us know:                                 \u2502\n\u2502      https://github.com/kubernetes/minikube/issues/new/choose\
        \                               \u2502\n\u2502                               \
        \                                                              \u2502\n\u2502\
        \    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub\
        \ issue.    \u2502\n\u2502                                                   \
        \                                          \u2502\n\u2570\u2500\u2500\u2500\u2500\
        \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\
        \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\
        \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\
        \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\
        \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\
        \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\
        \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u256F"

Signed-off-by: Nir Soffer <nsoffer@redhat.com>