Add drenv start --timeout option
This is useful when you want to avoid drenv start getting stuck, and the
environment does not provide a way to time out.

Example run:

    % drenv start --timeout 60 envs/vm.yaml
    2024-09-21 04:27:43,555 INFO    [vm] Starting environment
    2024-09-21 04:27:43,581 INFO    [cluster] Starting lima cluster
    2024-09-21 04:28:43,785 ERROR   [cluster] did not receive an event with the "running" status
    2024-09-21 04:28:43,790 ERROR   Command failed
    Traceback (most recent call last):
      ...
    drenv.commands.Error: Command failed:
       command: ('limactl', '--log-format=json', 'start', '--timeout=60s', 'cluster')
       exitcode: 1
       error:

For lima provider, we pass the timeout to limactl. For minikube we use
commands.watch() timeout. External provider does not use the timeout
since we don't start the cluster.

Signed-off-by: Nir Soffer <nsoffer@redhat.com>